kafka:
  streams:
    default:
      processing.guarantee: "exactly_once"
      auto.offset.reset: "earliest"
  bootstrap:
    servers: 127.0.0.1:9093
  security:
    protocol: SASL_PLAINTEXT
  sasl:
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="password123";
  consumers:
    mmo-server:
      bootstrap:
        servers: 127.0.0.1:9093
      session:
        timeout:
          ms: 30000
      auto:
        offset:
          reset: earliest